#
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

# Action to execute upstream integration tests - Edge Network (Konductor)
name: Integration Tests

on:
  # `*` is a special character in YAML so you have to quote this string
  # Avoiding start of hour and other common times to avoid conflicts with peak times
  schedule:
    # Run every weekday at 12:16 PM PDT (Daylight saving time) -> 7:16 PM UTC
    # Add +1 hour when back in PST
    - cron:  '16 19 * * 1-5'

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to use when running the integration tests.'
        required: false
        default: 'main'
      id:
        description: '(Optional) The identifier for the run.'
        required: false
      tags-mobile-property-id:
        type: string
        description: '(Optional) The tags mobile property ID to use for the test. A default is used if not set.'
        required: false
        default: ''
      edge-location-hint:
        type: choice
        description: '(Optional) The Edge location hint to set before each test.'
        required: false
        default: 'None'
        options:
          - 'aus3'
          - 'ind1'
          - 'irl1'
          - 'jpn3'
          - 'or2'
          - 'sgp3'
          - 'va6'
          - 'EmptyString'
          - 'Invalid'
          - 'None'
      ios-device-names:
        description: |
          The iOS device names to use for testing. Must be formatted as a valid JSON array string.
          Example: '["iPhone 15", "iPhone 15 Pro"]'
            - Notice the use of single quotes to wrap the JSON array string, and double quotes for each array element.
        type: string
        default: '["iPhone 15"]'
      ios-versions:
        description: |
          The iOS versions to use for testing. Must be formatted as a valid JSON array string.
          Example: '["18.0", "18.1"]'
            - Notice the use of single quotes to wrap the JSON array string, and double quotes for each array element.
        type: string
        default: '["18.0"]'
          

run-name: ${{ inputs.id }}

jobs:
  test-ios-integration:
    name: Integration Test (iOS)
    uses: adobe/aepsdk-commons/.github/workflows/ios-custom-command-build-and-test.yml@gha-ios-5.0.0
    with:
      ios-device-names: ${{ inputs.ios-device-names }}
      ios-versions: ${{ inputs.ios-versions }}
      command: make integration-test-ios TAGS_MOBILE_PROPERTY_ID=${{ github.event.inputs.tags-mobile-property-id }} EDGE_LOCATION_HINT=${{ github.event.inputs.edge-location-hint }}
      enable-codecov: false
    secrets: inherit
